version: '2.4'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    networks:
      default: { }
    ports:
      - "8123:8123"
    volumes:
      - ../custom_components:/config/custom_components
      - ./configuration.yaml:/config/configuration.yaml
